### ISSUE TITLE
Can't compile solution because of missing dependency to "Dinah.Core"

### ISSUE THREAD

**Issue by rkaregaran** [rmcrackan/AudibleApi#2]
Hey, just stumbled on your repo while searching for an API to Audible. Unfortunately, I can't compile because there appears to be a dependency on "Dinah.Core". Do you intend on including that dependency in your repo?

**Comment by ronazulaytransformant** [comment]
Im not the author, but you can find Dinah.Core in an earlier commit if you just want to try the example client:
https://github.com/rmcrackan/AudibleApi/tree/3ed0fab5989787cae131769b87e52903e6cc9b84

**Comment by ronazulay** [comment]
Found it in an earlier commit:
https://github.com/rmcrackan/AudibleApi/tree/3ed0fab5989787cae131769b87e52903e6cc9b84

**Comment by rkaregaran** [comment]
Thanks!
