### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 4Dmu** [rmcrackan/AudibleApi#23]
Hi again, is there a way to search the audible catalog? In the Api class definition there's a catalog path and  a content path, I've tried calling the catalog path with Api.AdHocAuthenticatedGetAsync() but the response is always a 403 no matter what variation I've tried.

**Comment by rmcrackan** [comment]
All calls should eventually make their way down through AdHoc. Which also means that you should be able to do anything through it. If you can get the get-library stuff to work then you'll know that you have the auth stuff correct. This is the hardest part. After that you should be able to make any other type of call. I recommend using @mkb79 's [great documentation](https://audible.readthedocs.io/en/latest/misc/external_api.html) as a reference.
