### ISSUE TITLE
Does this demo still work ?

### ISSUE THREAD

**Issue by tinoue** [rmcrackan/AudibleApi#3]
First of all, thank you for your nice Audible API client for C#.

I'm trying to run AudibleApiClientExample.
During build I god error about GitAllRepos. I removed dependency about it and managed to run AudibleClientExample.exe.

But it says:
---
3.1>AudibleApiClientExample.exe
Email:
XXXXXX@XXXX.com
Password:
********************CAPTCHA answer:
XXXXXX
ERROR:

{
  "error_code": null,
  "message": "ASIN XXXXXX not present in customer library."
}
https://api.audible.com/1.0/library/XXXXXXX?response_groups=badge_types,categ
ory_ladders,claim_code_url,contributors,is_downloaded,is_returnable,media,origin
_asin,pdf_url,percent_complete,price,product_attrs,product_desc,product_extended
_attrs,product_plan_details,product_plans,provided_review,rating,relationships,r
eview_attrs,reviews,sample,series,sku

---

I'm sure I have a vailid audible.com account and library.

**Comment by ronazulay** [comment]
(note, I am not the author)

Are you sure your library is in the US marketplace?
(https://audible.custhelp.com/app/answers/detail/a_id/7267/~/what-is-an-audible-marketplace-and-which-is-best-for-me%3F)

GetApiAsync() will use the US marketplace by default:
`GetApiAsync(string identityFilePath, ILoginCallback loginCallback = null, string localeCountryCode = "us")`

[https://github.com/rmcrackan/AudibleApi/blob/master/AudibleApi/locales.json](url)

**Comment by tinoue** [comment]
@ronazulay Yes. I have a valid account for US Amazon/Audible. Can you run the demo successfully ?

**Comment by tinoue** [comment]
I looked into source code of the demo and now it works. 
"ASIN XXXXXX not present in customer library." says all. Just because I don't have the book.
I modified the demo to call client.PrintLibraryAsync() and it runs fine (though I need to modify request parameter in PrintLibraryAsync()).
