### ISSUE TITLE
Better handling of timeout exceptions

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/AudibleApi#31]
Timeout exceptions can blow up the logs. See [this Libation issue](https://github.com/rmcrackan/Libation/issues/289#issuecomment-1163240854)

**Comment by rmcrackan** [comment]
I'd like to do this, but anything I can think of will also risk losing legitimately helpful parts of the log as well

**Comment by Mbucari** [comment]
Maybe use this approach?

https://stackoverflow.com/a/19822695/3335599

**Comment by Mbucari** [comment]
I've added better logging for http errors based on Exception info from https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-6.0

All http requests are run through ApiUnauthenticated.SendClientRequest.

**Comment by rmcrackan** [comment]
Gracias!

**Comment by Mbucari** [comment]
Well, I guess my fix didn't fix it.

https://github.com/rmcrackan/Libation/issues/302#issue-1285513880

I don't know why it's not catching the TaskCanceledException

**Comment by rmcrackan** [comment]
I don't think there's anything wrong with your fix. Libation issue 302 wasn't TaskCanceledException

    System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
    System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
