### ISSUE TITLE
Package unable to be installed because the newwest Comon package is not published 

### ISSUE THREAD

**Issue by luky92** [rmcrackan/AudibleApi#50]
As the title says package is not instalable due to newest common package not being published

**Comment by rmcrackan** [comment]
I just created a new hello world console with .net8 and added the nuget for the latest AudibleApi : 9.1.2.1. The console ran for me. We must be doing something different. Which step didn't work for you?

**Comment by luky92** [comment]
I was unable to reproduce it with windows sandbox I suggest trying a clean vm install ( I assume it got cashed somewhere

**Comment by luky92** [comment]
Can't reproduce currently I will reopen if I can reproduce
